/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.dmnem.poc20171103;
unit SuggestedLightInputUnit;

import java.time.LocalDateTime;

rule "SuggestedLightInputUnit_1"
when
	$input1 : Boolean() from isPresent
then
	System.out.println("I actually need to evaluate the input expression of the DT");
	suggestedLightInput1.insert($input1);
end

rule "SuggestedLightInputUnit_2"
when
	$input2 : String() from sunlight
then
	System.out.println("I actually need to evaluate the input expression of the DT");
	suggestedLightInput2.insert($input2);
end

rule "SuggestedLightInputUnit_guard"
when
	Boolean() from suggestedLightInput1
	String() from suggestedLightInput2
then
	System.out.println("I have all the inputs required to evaluate the DT I move to it");
	drools.guard(SuggestedLightDTUnit.class);
end
