/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.dmnem.poc20171103;
unit SuggestedLightDTUnit;

import java.time.LocalDateTime;

rule "SuggestedLightDTUnit-1"
when
	Boolean( this == false) from suggestedLightInput1
	// - as per don't care about input2
then
	System.out.println("SuggestedLight ROW 1");
	suggestedLightOutput1.insert( "OFF" );
end

rule "SuggestedLightDTUnit-2"
when
	Boolean( this == true) from suggestedLightInput1
	String ( this == "sunlight" ) from suggestedLightInput2
then
	System.out.println("SuggestedLight ROW 2");
	suggestedLightOutput1.insert( "OFF" );
end

rule "SuggestedLightDTUnit-3"
when
	Boolean( this == true) from suggestedLightInput1
	String ( this == "night time" ) from suggestedLightInput2
then
	System.out.println("SuggestedLight ROW 3");
	suggestedLightOutput1.insert( "ON" );
end

